[package]
name = "ozsynth"
version = "0.1.0"
edition = "2018"

[lib]
name = "ozsynth"
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21", default-features = false }
lazy_static = "1.4"

[profile.release]
strip = "none"
opt-level = "z"
lto = false
codegen-units = 1
panic = "abort"
